const names = [
  "SMS_PROVIDER",
  "LIVE_SMS_ENABLED",
  "SMS_OUTBOUND_VERIFIED",
  "APP_MODE",
  "PURCHASE_ENABLED",
  "AGENTPHONE_API_KEY",
  "AGENTPHONE_AGENT_ID",
  "AGENTPHONE_NUMBER_ID",
  "AGENTPHONE_PHONE_NUMBER",
  "AGENTPHONE_WEBHOOK_SECRET",
  "AGENTPHONE_AGENT_SEPARATION_CONFIRMED",
  "AGENTPHONE_WEBHOOK_SETUP_ENABLED",
  "AGENTPHONE_WEBHOOK_REMOTE_VERIFIED",
  "PUBLIC_WEBHOOK_URL",
  "ALLOWED_PHONES",
  "ADMIN_PHONE",
  "DATA_ENCRYPTION_KEY",
  "PII_HASH_KEY",
  "DATABASE_PATH",
  "DOORDASH_ACCOUNT_CONNECTED_VERIFIED",
  "DOORDASH_CLI_PATH",
  "DD_CLI_ACCESS_TOKEN",
  "DOORDASH_DEMO_CART_UUID"
] as const;

for (const name of names) {
  const value = process.env[name];
  process.stdout.write(`${name}=${value && value.trim() ? "[set]" : "[missing]"}\n`);
}
